In [5]:
# dependencies
#!conda install --yes -c conda-forge fastparquet   in jupyter notebook not recommended, download it from terminal
import pandas as pd

# Data Cleaning

This notebook is solely for data cleaning purposes only, after the cleaning please write the data to data/out, and for the code please create another data_cleaning.py script under src.

In [10]:
df = pd.read_parquet("../data/DSC180B.parquet",engine='auto')
df

,transaction_date,amount,memo,new_category
8,2018-03-06,15.25,POS CASINO BAR @ SPOTL - MEMO=PURCHASE 03/02 C...,Entertainment
39,2018-09-29,16.04,BEST BUY GRAND REGENCY BRANDON F,General Merchandise
45,2018-10-17,10.36,CORNER STORE ARLINGTON TX 10/17 Purchase $5.3...,Automotive
52,2017-07-11,4.63,SPEEDWAY IN BEDFORD IN 07/10 DEBIT_CARD,Automotive
55,2018-09-10,223.00,PAYMENT FOR AMZ STORECARD WEB ID: ACH_DEBIT,General Merchandise
...,...,...,...,...
1999981,2021-02-19,24.24,DBT/WDR CASEYS GEN STORE FENNIMORE WI,Automotive
1999982,2021-01-19,120.60,POS Debit - DDA KOHLS CLIVE IA #,General Merchandise
1999983,2022-02-25,6.47,STARBUCKS STORE MAPLE VALLEY WA 02/24,Food and Beverages
1999991,2021-01-11,44.98,POS Debit - Visa Check Card - APPLE.COM/BILL ...,General Merchandise
1999992,2022-04-11,1.00,NAYAX VENDING 2 HUNT VALLEY MD 0...,Food and Beverages